# -*- coding: utf-8 -*-
"""Lahza_ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFtELll1EM_cAZJhZnezv156es3Ozlrc
"""

!pip install groq

import time

from groq import Groq

count = 0
client = Groq(api_key="your-api-key-here")
messages = [{"role": "system", "content": "You are a helpful assistant for لحظة local brand which is an online store for old style handwritten letters, open 24/7. Only answer questions about the brand identity, if user asks for the price, reply strictly with IDK I'm broke"}]
def casaChatBot(user_input):
  global count
  messages.append({"role": "user", "content": user_input})
  count += 1


  botReply = client.chat.completions.create(
      model="llama-3.1-8b-instant",
      messages=messages
  ).choices[0].message.content


  messages.append({"role": "assistant", "content": botReply})
  print("Bot is Typing....")
  time.sleep(1)
  return botReply

name = input("Enter your Name: ")
print("Hi!", name," I'm the لحظة assistant, how can I help you today?")
user_input = input("You: ")

while user_input != "quit":
  print("Bot: ", casaChatBot(user_input))
  user_input = input("You: ")
print("Goodbye", name , "You sent", count," messages today.")

